services:
    basecode_db:
        container_name: basecode_db
        image: 'postgres:16.4-alpine3.20'
        environment:
            PGUSER: ${POSTGRES_USER}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_NAME}
        ports:
            - '${POSTGRES_EXPOSE_PORT}:5432'
        volumes:
            # - ./ext.sql:/docker-entrypoint-initdb.d/ext.sql
            - ./dbdata:/var/lib/postgresql/data/:delegated
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 10s
            timeout: 5s
            retries: 18

    basecode_db_atlas:
        container_name: basecode_db_atlas
        image: 'postgres:16.4-alpine3.20'
        environment:
            PGUSER: ${POSTGRES_USER}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_NAME}

    basecode_backend:
        container_name: basecode_backend
        build:
            context: ../backend
            dockerfile: ../docker/dockerfiles/backend
        volumes:
            - ../backend:/code:delegated
        environment:
            GOPATH: /code/
            SECRET_KEY: ${SECRET_KEY}
            TIME_ZONE: ${TIME_ZONE}
            DEBUG: ${DEBUG}

            APP_TITLE: ${APP_TITLE}
            APP_DESCRTIPTION: ${APP_DESCRTIPTION}

            PORT: ${PORT}
            PROTOCOL: ${PROTOCOL}
            DOMAIN: ${DOMAIN}

            DB_HOST: ${POSTGRES_HOST}
            DB_PORT: ${POSTGRES_PORT}
            DB_USER: ${POSTGRES_USER}
            DB_NAME: ${POSTGRES_NAME}
            DB_PASSWORD: ${POSTGRES_PASSWORD}
            DB_URL: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_NAME}?sslmode=disable'
            DB_URL_ATLAS: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST_ATLAS}:${POSTGRES_PORT}/${POSTGRES_NAME}?sslmode=disable'

            EMAIL_ENABLE: ${EMAIL_ENABLE}
            EMAIL_DOMAIN: ${EMAIL_DOMAIN}
            EMAIL_HOST: ${EMAIL_HOST}
            EMAIL_PORT: ${EMAIL_PORT}
            EMAIL_HOST_USER: ${EMAIL_HOST_USER}
            EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
            EMAIL_USE_TLS: ${EMAIL_USE_TLS}
        ports:
            - '4000:4000'
        depends_on:
            basecode_db:
                condition: service_healthy
        tty: ${DOCKER_TTY}
        command: ${DOCKER_COMMAND}

    basecode_frontend:
        container_name: basecode_frontend
        build:
            context: ../frontend
            dockerfile: ../docker/dockerfiles/frontend
        volumes:
            - ../frontend:/code:delegated
            - /code/node_modules
        ports:
            - '3000:3000'
        tty: ${DOCKER_TTY}

    basecode_nginx:
        container_name: basecode_nginx
        build:
            context: ./
            dockerfile: ./dockerfiles/nginx
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d
            - ${SSL_PATH}:/resource/ssl
            - ../backend/public/:/resource/public
        ports:
            - '443:443'
        depends_on:
            - basecode_backend
